channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pip=23.2.1
    - pip:
        - mkdocs-material==9.3.1
        - mike==1.1.2
        - mkdocstrings-python==1.16.12
        - setuptools
